services:
  db:
    image: postgres:latest
    container_name: erp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_forte
      POSTGRES_DB: erp_db
    ports:
      - "5432:5432"